blank_issues_enabled: true

contact_links:
  - name: Metaxone Solution
    url: https://metaxonesolution.com/
    about: Ask and discuss about LunarVim on Matrix.
  - name: Discord community
    url: https://discord.gg/dHY2QGc9Zu
    about: Ask and discuss about Cyberonix on Discord.
